#!/bin/bash
### BEGIN INIT INFO
# Provides:          stampzilla
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start stampzilla daemons at boot time
# Description:       Enables stampzilla homeautomation daemons
### END INIT INFO

case "$1" in
	start|stop|status|restart)
		stampzilla $@
		;;
  	*)
		echo "Usage: /etc/init.d/stampzilla {start|stop|restart|force-reload}" >&2
		exit 3
	;;
esac

:
