#!/bin/bash

rm /usr/bin/stampzilla
rm /usr/share/stampzilla
rm /usr/lib/stampzilla
rm /usr/share/man/man1/stampzilla.1.gz

if [ `command -v update-rc.d` ]; then
    rm /etc/init.d/stampzilla
    update-rc.d stampzilla remove
fi

confd=`php --ini|grep 'additional'|awk '{print $7;}'`
rm $confd
